### ISSUE TITLE
Add new unit tests with Jest

### ISSUE THREAD

**Issue by DylanP97** [DylanP97/next13-apprentissage-de-la-conduite#3]
We want to add more coverage into our project components.
You can create new tests and new mocks into their corresponding directories.

**Comment by FloPetra** [comment]
Hi, can you assign this issue to me, please?

**Comment by DylanP97** [comment]
Done

**Comment by DylanP97** [comment]
Hi,
Let me know when you think you would finish ;)

**Comment by FloPetra** [comment]
Heey, you will definitely have it by end of this week if that works.
I aim for Friday :)

**Comment by DylanP97** [comment]
Amazing, thanks!
Do what you can, there's no pressure or specific goals
